import { Geist,Inter  } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import HeroUiThemeProvider from "@/provider/HeroUiThemeProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${inter.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className={`min-h-full flex flex-col bg-background text-foreground ${inter.className}`}>
       <HeroUiThemeProvider>
         <NavBar/>
        <main className="">
         <div className="max-w-6xl mx-auto p-1">
           {children}
         </div>
        </main>
        <Footer/>
        <ToastContainer />
       </HeroUiThemeProvider>
      </body>
    </html>
  );
}
